apiVersion: v1                 # API version for Services
kind: Service                  # Type of Kubernetes object
metadata:
  name: react-app-service      # Name of your service
spec:
  selector:
    app: react-app             # Selects pods with the label 'app: react-app'
  ports:
    - protocol: TCP            # Protocol for the port
      port: 80                 # Port the service will be accessible on (inside the cluster)
      targetPort: 80           # Port on the pod that the service forwards traffic to (your Nginx port)
  type: NodePort               # Type of service:
                          